import json
import os

from fastapi import APIRouter

router = APIRouter(prefix="/api", tags=["dashboard"])

# The static site's data/data_export.json + data/safety_export.json are the
# same pre-aggregated data this app serves — re-reading them here rather
# than duplicating the aggregation logic. They're static (regenerated by the
# analyze*.py scripts, not per-request), so one passthrough endpoint each is
# the right call, not seven near-identical ones.
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
_DATA_EXPORT = os.path.join(_REPO_ROOT, "data", "data_export.json")
_SAFETY_EXPORT = os.path.join(_REPO_ROOT, "data", "safety_export.json")

_cache: dict = {}


def _sanitize_nan(obj):
    """The source export (written by scripts/analyze*.py via plain
    json.dump) contains literal NaN tokens for a handful of missing values
    (e.g. Lucid's tailpipe CO2, since it's 100% electric some model years).
    That's technically invalid JSON, but the static site never notices
    because it's embedded via a raw <script> literal, where NaN is a valid
    JS keyword — not run through JSON.parse. A real API response is a
    different contract: a standards-compliant client's fetch().json() will
    reject a literal NaN in the response body outright, so it has to become
    null before this ever reaches a client."""
    if isinstance(obj, float) and obj != obj:  # NaN != NaN is the classic float check
        return None
    if isinstance(obj, dict):
        return {k: _sanitize_nan(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize_nan(v) for v in obj]
    return obj


def _load(path: str, key: str):
    if key not in _cache:
        with open(path, encoding="utf-8") as f:
            _cache[key] = _sanitize_nan(json.load(f))
    return _cache[key]


@router.get("/dashboard-data")
def get_dashboard_data():
    return _load(_DATA_EXPORT, "dashboard")


@router.get("/safety-data")
def get_safety_data():
    return _load(_SAFETY_EXPORT, "safety")
